version: "3.9"

services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toho-app
    ports:
      - "5500:5500" # Map port lokal ke container
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: toho-redis
    ports:
      - "6380:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: toho-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
